name: Update

on:
  schedule:
    - cron: '0 0 * * *' # 毎日UTC 0時に実行します。
  workflow_dispatch: # この行を追加して手動トリガーを許可します。

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # 全てのコミット履歴を取得します。

    - name: Configure git
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "github-action"

    - name: Execute update_json.sh script
      run: bash update_json.sh

    - name: Commit and push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
